name: Rust Test

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      changed:
        required: true
        type: boolean

jobs:
  run:
    if: ${{ inputs.changed }}
    name: Cargo Test
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: moonrepo/setup-rust@v1
        with:
          bins: just
          cache-base: main

      - name: Build
        run: cargo test --workspace --exclude rolldown_binding --no-run

      - name: Run Test
        run: cargo test --workspace --exclude rolldown_binding --nocapture
